version: "2"
services:
  node:
    image: "node:14"
    user: "node"
    working_dir: /usr/src/app
    ports:
      - "5001:5001"
    volumes:
      - ./:/usr/src/app
    networks:
      neodata:
        ipv4_address: 10.0.100.58
    command: bash -c "npm install && node index.js"

networks:
  neodata:
    external: true